<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
